#! /bin/sh
### BEGIN INIT INFO
# Provides:          ocxopll
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start the ocxo pll
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

ROOT=/root

do_start() {
    insmod ${ROOT}/modules/ocxo.ko
    insmod ${ROOT}/modules/pps-fpga.ko

    # Set the fan speed to around 50%
    ${ROOT}/bin/poke 0x80600200 135

    # Start the pll and send the output as UDP broadcast
    ${ROOT}/bin/pll.pl | nc -u -b 192.168.124.255 4010&

    # Initially set the time and display the time
    ${ROOT}/bin/settime.sh
    ${ROOT}/bin/rottime.sh &
    
    # Wait for the pll to lock
    sleep 800
    ${ROOT}/bin/settime.sh
    service ntp start
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

exit 0
