#! /bin/sh
### BEGIN INIT INFO
# Provides:          ocxopll
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the ocxo pll
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

ROOT=/root

do_start() {
    insmod ${ROOT}/modules/ocxo.ko
    insmod ${ROOT}/modules/pps-fpga.ko

    # Set the fan speed to around 50%
    ${ROOT}/bin/poke 0x80600200 135

    # Start the pll and send the output as UDP broadcast
    ${ROOT}/bin/pll.pl -a 1 | nc -u -b 192.168.124.255 4010&

    # Display the time
    ${ROOT}/bin/rottime.sh &
    
    # Wait for the pll to lock
    sleep 800 && service ntp start&
}

do_stop() {
    # Stop the ntp service
    service ntp stop
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	do_stop
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

exit 0
